#!/bin/bash
#
# Stage all, commit with message and push to master
#

# Output colors
r='\033[01;31m' #red
b='\033[01;34m' #blue
g='\033[01;32m' #green
n='\033[00m' #normal

EXPECTED_ARGS=1
BADARGS_ERROR=65

if [ $# -ne ${EXPECTED_ARGS} ]; then
    echo -e "\nUsage: $0 \"Commit message\"\n"
    exit ${BADARGS_ERROR}
fi

echo -e "\n${b}- Stage all changes within the working space${n}\n${b}- Commit with the message \"${r}${1}${b}\"${n}\n${b}- Push to origin, master branch\n${n}"

git add -A && echo -e "${b}Stage ---> [${g}OK${b}]${n}" || echo -e "${b}Stage ---> [${r}BAD${b}]${n}"
git commit -m "${1}" && echo -e "${b}Commit ---> [${g}OK${b}]${n}" || echo -e "${b}Commit ---> [${r}BAD${b}]${n}"
git push origin master && echo -e "${b}Push ---> [${g}OK${b}]${n}" || echo -e "${b}Push ---> [${r}BAD${b}]${n}"
echo -e " "

#End of the script
